default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>

development:
  <<: *default
  database: react_rails_development
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { '' }%>

test:
  <<: *default
  database: react_rails_test
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { '' }%>

production:
  url: <%= ENV.fetch('DATABASE_URL') { '' } %>
  database: attribute
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { '' }%>
